const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'});
require('dotenv').config()


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: process.env.HOST,
    basePath: "/",
    // schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    component: {
        SecurityChemes:{
            bearerAuth:{
                type: 'http',
                scheme: 'bearer'
            }
        }
    },
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // Your project's root file
})